### ISSUE TITLE
SystemMessage can not cast ContextContainer

### ISSUE THREAD

**Issue by luojiangyu** [kamon-io/kamon-akka-remote#17]
Caused by: java.lang.ClassCastException: akka.dispatch.sysmsg.Supervise cannot be cast to kamon.akka.context.ContextContainer
	at akka.kamon.instrumentation.RemotingInstrumentation.applyCurrentContext(RemotingInstrumentation.scala:66)
	at akka.kamon.instrumentation.RemotingInstrumentation.afterSendSystemMessageMessageInActorCell(RemotingInstrumentation.scala:60)
	at akka.actor.ActorCell.sendSystemMessage(ActorCell.scala:374)
	at akka.actor.LocalActorRef.sendSystemMessage(ActorRef.scala:404)
	at akka.actor.dungeon.Dispatch$class.init(Dispatch.scala:80)
	at akka.actor.ActorCell.init(ActorCell.scala:374)
	at akka.actor.LocalActorRef.<init>(ActorRef.scala:326)
	at akka.actor.LocalActorRefProvider.guardian$lzycompute(ActorRefProvider.scala:631)
	at akka.actor.LocalActorRefProvider.guardian(ActorRefProvider.scala:628)
	at akka.actor.LocalActorRefProvider.systemGuardian$lzycompute(ActorRefProvider.scala:642)
	at akka.actor.LocalActorRefProvider.systemGuardian(ActorRefProvider.scala:638)
	at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:665)
	at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:183)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:828)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:825)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:825)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:841)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:245)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:288)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:263)
	at akka.actor.ActorSystem$.create(ActorSystem.scala:191)

**Comment by ivantopo** [comment]
Hey @luojiangyu, could you please share a bit more of context? like, what versions are you running? how are you packaging the application?

**Comment by luojiangyu** [comment]
the version  is kamon-akka-remote-2.4_2.11
`
application.conf
{
	"akka": {
		"actor": {
			"default-dispatcher": {
				"fork-join-executor": {
					"parallelism-factor": 2
				},
				"throughput": 15
			},
			"guardian-supervisor-strategy": "org.apache.flink.runtime.akka.StoppingSupervisorWithoutLoggingActorKilledExceptionStrategy",
			"provider": "akka.remote.RemoteActorRefProvider",
			"warn-about-java-serializer-usage": "off"
		},
		"daemonic": "off",
		"jvm-exit-on-fatal-error": "on",
		"log-config-on-start": "off",
		"log-dead-letters": "off",
		"log-dead-letters-during-shutdown": "off",
		"loggers": ["akka.event.slf4j.Slf4jLogger"],
		"logging-filter": "akka.event.slf4j.Slf4jLoggingFilter",
		"loglevel": "INFO",
		"remote": {
			"log-remote-lifecycle-events": "off",
			"netty": {
				"tcp": {
					"bind-hostname": "0.0.0.0",
					"bind-port": 44715,
					"connection-timeout": "20 s",
					"hostname": "test01",
					"maximum-frame-size": "10485760b",
					"port": 44715,
					"tcp-nodelay": "on",
					"transport-class": "akka.remote.transport.netty.NettyTransport"
				}
			},
			"startup-timeout": "10 minutes",
			"transport-failure-detector": {
				"acceptable-heartbeat-pause": "6000 s",
				"heartbeat-interval": "1000 s",
				"threshold": 300
			},
			"watch-failure-detector": {
				"acceptable-heartbeat-pause": "60 s",
				"heartbeat-interval": "5 s",
				"threshold": 12
			}
		},
		"serialize-messages": "off",
		"stdout-loglevel": "OFF"
	},
	"kamon": {
		"util": {
			"filters": {
				"akka.tracked-actor": {
					"includes": ["flink/user/jobmanager", "flink/user/resourcemanager", "flink/user/taskmanager"]
				},
				"akka.tracked-dispatcher": {
					"includes": ["flink/akka.actor.default-dispatcher"]
				},
				"akka.tracked-router": {
					"includes": ["flink/*"]
				}
			}
		}
	}
}`

thanks .

**Comment by luojiangyu** [comment]
> Hey @luojiangyu, could you please share a bit more of context? like, what versions are you running? how are you packaging the application?

what is the problem？ how  to solve  the problem ？ 

Thanks.
